export global AppImages {
    out property <image> img-icon: @image-url("assets/icon.png");
    out property <image> img_button_up: @image-url("assets/button_up.svg");
    out property <image> img_button_down: @image-url("assets/button_down.svg");
    out property <image> img_background: @image-url("assets/background.png");
}
export global AppGlobal {
    out property<brush> background: #1673b4;
    out property<brush> alternate-background: #2296bc;
    out property<brush> foreground: white;
}