import { GroupBox,CheckBox, Button,LineEdit,ComboBox,TabWidget,
    SpinBox,Slider } from "std-widgets.slint";
export  component MainWindow inherits Window {
    in-out property <string> current_path;
    in-out property <float> page_width_mm: 297;
    in-out property <float> page_height_mm: 210;
    in-out property <int> center_width_mm <=> center_width.value;
    in-out property <int> column_count <=> col_count.value;
    in-out property <int> page_left_margin_mm <=> page_left_margin.value;
    in-out property <int> page_top_margin_mm <=> page_top_margin.value;
    in-out property <int> tail_margin_mm <=>tail_margin.value;
    in-out property <string> input_path <=> input_path_line.text;   
    in-out property <string> book_name <=> book_name_line.text;
    in-out property <string> output_path <=> output_path_line.text;
    in-out property <float> compress_ratio <=> compress_ratio_slider.value; 
    in-out property <string> config_path <=> config_path_line.text;
    in-out property <string> font_color <=> font_color_com.current-value;
    in-out property <string> background_color <=> bg_color_com.current-value;
    in-out property <string> draw_color <=> draw_color_com.current-value;
    in-out property <string> font_path <=> font_path_line.text;
    in-out property <string> font_backup_path <=> font_backup_path_line.text;

    callback create_pdf();
    callback pdf_compress_gs();
    callback get_config();
    callback save_config();
    
    width: 960px;
    height: 600px;
    default-font-size: 16px;
    title: "古籍电子书制作";
    background: #f7f4f4;
    // 设置窗口图标
    icon: @image-url("icon.png");          
    VerticalLayout {
        width: 90%;
        height: 100%;
        spacing: 10px;
        HorizontalLayout {
            height: 3%;
            spacing: 10px;
            alignment: center;                
        }
        HorizontalLayout {
            spacing: 10px;
            VerticalLayout {
                spacing: 10px;
                HorizontalLayout {
                    height: 10%;
                    spacing: 10px;
                    Text {
                        height: 50px;
                        text: "画布尺寸";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    LineEdit {
                        height: 50px;
                        text: page_width_mm;
                        read-only: true;
                    }
                    Text {
                        height: 50px;
                        text: "*";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    LineEdit {
                        height: 50px;
                        text:   page_height_mm;
                        read-only: true;
                    }
                    Text {
                        height: 50px;
                        text: "中心宽";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    center_width:=SpinBox {
                        height: 50px;
                        value: 20;
                        minimum: 18;
                        step-size: 2;
                        maximum: 24;
                        edited(value) => {
                            center_width_mm = value;
                        }
                    }
                    Text {
                        height: 50px;
                        text: "总列数";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    col_count:=SpinBox {
                        height: 50px;
                        value: 20;
                        minimum: 20;
                        step-size: 2;
                        maximum: 26;
                        edited(value) => {
                            column_count = value;
                        }
                    }
                } 
                HorizontalLayout {
                    height: 10%;
                    spacing: 10px;
                    Text {
                        height: 50px;
                        text: "上侧留白";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    page_top_margin:=SpinBox {
                        height: 50px;
                        value: 20;
                        minimum: 10;
                        maximum: 25;
                        step-size: 1;
                        edited(value) => {
                            page_top_margin_mm = value;
                        }
                    }
                    Text {
                        height: 50px;
                        text: "边框留白";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }   
                    page_left_margin:=SpinBox {
                        height: 50px;
                        value: 8;
                        minimum: 6;
                        maximum: 10;
                        step-size: 1;
                        edited(value) => {
                            page_left_margin_mm = value;
                        }
                    }
                    Text {
                        height: 50px;
                        text: "鱼尾留白";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    tail_margin:=SpinBox {
                        height: 50px;
                        value: 30;
                        minimum: 24;
                        maximum: 36;
                        step-size: 1;
                        edited(value) => {
                            tail_margin_mm = value;
                        }
                    }                    
                }    
                HorizontalLayout {
                    height: 10%;
                    spacing: 10px;
                    Text {
                        height: 50px;
                        text: "背景颜色";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    bg_color_com:=ComboBox {
                        height: 50px;
                        model: ["白", "泛黄", "浅黄", "灰黄", "旧书", "深黄"];
                        current-value: "泛黄";
                        selected(current-value) => {
                            background_color = current-value;
                        }
                    }
                    Text {
                        height: 50px;
                        text: "边框颜色";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    draw_color_com:=ComboBox {
                        height: 50px;
                        model: ["黑", "红", "蓝", "绿", "褐", "深灰", "墨"];
                        current-value:  "黑";
                        selected(current-value) => {
                            draw_color = current-value;
                        }
                    }
                    Text {
                        height: 50px;
                        text: "字体颜色";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    font_color_com:=ComboBox {                                    
                        height: 50px;
                        model: ["黑", "红", "蓝", "绿", "褐", "深灰", "墨"];
                        current-value: "黑";
                        selected(current-value) => {
                            font_color = current-value;
                        }
                    }
                }                  
                HorizontalLayout {
                    height: 10%;
                    spacing: 10px;
                    Text {
                        height: 50px;
                        text: "主要字体";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    font_path_line:=LineEdit {
                        height: 50px;
                        text: current_path + "/fonts/XiaolaiMonoSC-Regular.ttf";
                        edited(text) => {
                            font_path = text;
                        }
                    }
                    Text {
                        height: 50px;
                        text: "备用字体";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    font_backup_path_line:=LineEdit {
                        height: 50px;
                        text: current_path + "/fonts/simfang-lite.ttf";
                        edited(text) => {
                            font_backup_path = text;
                        }
                    }
                }  
                HorizontalLayout {
                    width: 90%; 
                    height: 10%;
                    spacing: 10px;
                    Text {
                        height: 50px;
                        text: "书籍名称";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    book_name_line:=LineEdit {
                        height: 50px;
                        text: "庄子";
                        edited(text) => {
                            book_name = text;
                        }
                    }
                    Text {
                        height: 50px;
                        text: "配置文件";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    config_path_line:=LineEdit {
                        height: 50px;
                        text: current_path + "/config.json";
                        edited(text) => {
                            config_path = text;
                        }
                    } 
                } 
                HorizontalLayout {
                    height: 10%;
                    spacing: 10px;                    
                    Text {
                        height: 50px;
                        text: "输入文本";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    input_path_line:=LineEdit {
                        height: 50px;
                        text: current_path + "/text/001.txt";
                        edited(text) => {
                            input_path = text;
                        }
                    }
                    Text{
                        height: 50px;
                        text: "输出文件";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    output_path_line:=LineEdit {
                        height: 50px;
                        text: current_path + "/pdf/庄子.pdf";
                        read-only: false;
                        edited(text) => {
                            output_path = text;
                        }
                    } 
                }                                      
                HorizontalLayout {
                    height: 10%;
                    spacing: 10px;
                    Text {
                        width: 100px;
                        height: 50px;
                        text: "压缩参数";
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;
                    }
                    compress_ratio_slider:=Slider {                                    
                        height: 50px;                            
                        minimum: 10;
                        maximum: 100;
                        step: 1;
                        value: 80;
                        changed(value) => {
                            compress_ratio = Math.round(value);
                        }
                    }
                    compress_ratio_text:=Text {
                        height: 50px;
                        text: Math.round(compress_ratio);
                        vertical-alignment: center;
                        font-size: 20px;                                       
                        color: black;                                    
                    }
                }
            }
        }
        HorizontalLayout {
            spacing: 10px;
            alignment: center;                
            Button {
                width: 150px;
                height: 50px;
                text: "生成PDF"; 
                clicked => {
                    create_pdf();
                }
            }
            Button {
                width: 150px;
                height: 50px;
                text: "GS压缩PDF"; 
                clicked => {
                    pdf_compress_gs();
                }
            }
            Button {
                width: 150px;
                height: 50px;
                text: "加载配置"; 
                clicked => {
                    get_config();
                }
            }
            Button {
                width: 150px;
                height: 50px;
                text: "保存配置"; 
                clicked => {
                    save_config();
                }
            }
        }
    }
}

